
title: Jacek Rojek Portfolio
email: j.rojek19@gmail.com
description: > 
  Web Developer, freelancer... Experienced in Front-end:HTML, CSS3/SASS+compass ,JavaScript/EM6/coffeeScript, jQuery, AJAX. Back-End: PHP, MySQL
baseurl: "/MyPortfolio" 
url: "http://jacekrojek.github.io" 
twitter_username: JRojek93
github_username:  JacekRojek

# Build settings
markdown: kramdown
theme: minima
include: ['_pages']
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
